<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Apply</name>
   <tag></tag>
   <elementGuidId>c109570e-8755-47a9-b8dc-0b0a224214cb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@href = 'https://marvell.wd2.myworkdayjobs-impl.com/en-US/MarvellCareers/details/Senior-Staff-Systems-Applications-Engineer---Ethernet-PHY_2300850/apply' and @class = 'css-1meq8ta' and (text() = 'Apply' or . = 'Apply')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.css-1meq8ta</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8364443e-0857-4ba9-aea6-de2e6796bf9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://marvell.wd2.myworkdayjobs-impl.com/en-US/MarvellCareers/details/Senior-Staff-Systems-Applications-Engineer---Ethernet-PHY_2300850/apply</value>
      <webElementGuid>6cbbc9a4-3263-4dd6-9f92-b0e625bfb2c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>87dd47f3-8cc0-45fd-b4df-73c16d4f088b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-automation-id</name>
      <type>Main</type>
      <value>adventureButton</value>
      <webElementGuid>1744d309-7156-4cf2-9b29-6c2a9dd7d7a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>font-size</name>
      <type>Main</type>
      <value>14</value>
      <webElementGuid>b26c2529-305c-4673-97fe-c18fa0490505</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>3ef84632-0810-4af5-9094-b380a47fddb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-1meq8ta</value>
      <webElementGuid>825da0df-9b22-4c45-8ba6-51dfd96cf4a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Apply</value>
      <webElementGuid>cce1bc22-61b3-411f-b1c0-39aa80a16069</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainContent&quot;)/div[@class=&quot;css-b4ple3&quot;]/div[@class=&quot;css-uvpbop&quot;]/div[1]/div[@class=&quot;css-1s8xnc9&quot;]/section[@class=&quot;css-1v46q50&quot;]/div[@class=&quot;css-47ru22&quot;]/div[@class=&quot;css-6su6fj&quot;]/div[@class=&quot;css-2c41hv&quot;]/div[@class=&quot;css-1f9tql3&quot;]/div[@class=&quot;css-18k4i7e&quot;]/div[@class=&quot;css-37urdo&quot;]/div[@class=&quot;css-ipzqjw&quot;]/div[@class=&quot;css-b3pn3b&quot;]/div[@class=&quot;css-b3pn3b&quot;]/a[@class=&quot;css-1meq8ta&quot;]</value>
      <webElementGuid>10fc2774-377f-4be7-ac8b-057acf1cf61f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://marvell.wd2.myworkdayjobs-impl.com/en-US/MarvellCareers/details/Senior-Staff-Systems-Applications-Engineer---Ethernet-PHY_2300850/apply' and @class = 'css-1meq8ta' and (text() = 'Apply' or . = 'Apply')]</value>
      <webElementGuid>961e8403-747b-4011-aff4-2828cc20503c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mainContent']/div/div[2]/div/div/section/div/div/div[3]/div/div/div[2]/div/div/div/a</value>
      <webElementGuid>81881667-2e8b-4d7d-9ce5-27f477064b0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Apply')]</value>
      <webElementGuid>50a64773-c96f-460e-9a51-7fb1578e719e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Senior Staff Systems Applications Engineer – Ethernet PHY'])[2]/following::a[2]</value>
      <webElementGuid>db435ccb-076d-4e5e-97b1-7c61dde319af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Return to selected search result'])[1]/following::a[2]</value>
      <webElementGuid>cf217d90-95e5-4d93-84fd-8b7e10f8ecae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='locations'])[21]/preceding::a[1]</value>
      <webElementGuid>006f6c87-530e-4a5a-9166-7ffa80b0dfa6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Santa Clara, CA'])[7]/preceding::a[1]</value>
      <webElementGuid>63e09325-2d9b-49ce-8af4-0e3f01a9dec1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Apply']/parent::*</value>
      <webElementGuid>4df94435-81d3-4502-85c7-4dde566367ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://marvell.wd2.myworkdayjobs-impl.com/en-US/MarvellCareers/details/Senior-Staff-Systems-Applications-Engineer---Ethernet-PHY_2300850/apply')]</value>
      <webElementGuid>e58ce2c0-a41d-42a2-b413-b942d671bc21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/a</value>
      <webElementGuid>6f541f21-7c5d-4336-b155-2465b39dba50</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
