<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Senior Staff Systems Applications Enginee_9828fd</name>
   <tag></tag>
   <elementGuidId>3be0e699-cecf-49d2-839f-5392b42f338c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@class = 'css-19uc56f' and @href = '/en-US/MarvellCareers/job/Santa-Clara-CA/Senior-Staff-Systems-Applications-Engineer---Ethernet-PHY_2300850' and (text() = 'Senior Staff Systems Applications Engineer – Ethernet PHY' or . = 'Senior Staff Systems Applications Engineer – Ethernet PHY')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.css-19uc56f</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7d33919a-1092-4d48-9ff2-77e6b8583d9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-current</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>453d22b7-3b2b-4796-9e07-c7d4f8e7dff9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-automation-id</name>
      <type>Main</type>
      <value>jobTitle</value>
      <webElementGuid>85a07160-ee2a-4185-ac2e-ff0d444985ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-uxi-element-id</name>
      <type>Main</type>
      <value>jobItem</value>
      <webElementGuid>0a1ca187-9f79-4ea4-a4ce-3e913eb7878b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-uxi-query-id</name>
      <type>Main</type>
      <value>7b100b47-f76e-480b-a74d-9bb9d0ead8bc</value>
      <webElementGuid>abdd7af3-9c53-4cc1-a80b-8d8e9300574e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-uxi-widget-type</name>
      <type>Main</type>
      <value>heading</value>
      <webElementGuid>46f9b9b0-598d-4179-842d-06b0853e2d4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-19uc56f</value>
      <webElementGuid>3ec02d60-ef6a-4aa4-b387-7af3285235c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/en-US/MarvellCareers/job/Santa-Clara-CA/Senior-Staff-Systems-Applications-Engineer---Ethernet-PHY_2300850</value>
      <webElementGuid>95181742-7ff1-460c-916a-c473befb9c06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Senior Staff Systems Applications Engineer – Ethernet PHY</value>
      <webElementGuid>61f78e28-ecbe-488b-bffc-4467971d0f88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainContent&quot;)/div[@class=&quot;css-b4ple3&quot;]/div[@class=&quot;css-uvpbop&quot;]/section[@class=&quot;css-8j5iuw&quot;]/ul[1]/li[@class=&quot;css-1q2dra3&quot;]/div[@class=&quot;css-qiqmbt&quot;]/div[@class=&quot;css-b3pn3b&quot;]/div[@class=&quot;css-b3pn3b&quot;]/h3[1]/a[@class=&quot;css-19uc56f&quot;]</value>
      <webElementGuid>2531f940-a955-4811-b072-652a5e15b2e7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@class = 'css-19uc56f' and @href = '/en-US/MarvellCareers/job/Santa-Clara-CA/Senior-Staff-Systems-Applications-Engineer---Ethernet-PHY_2300850' and (text() = 'Senior Staff Systems Applications Engineer – Ethernet PHY' or . = 'Senior Staff Systems Applications Engineer – Ethernet PHY')]</value>
      <webElementGuid>1e74a18b-5d61-4b78-afa9-0c87c2641bd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mainContent']/div/div[2]/section/ul/li/div/div/div/h3/a</value>
      <webElementGuid>a397c2cd-f32f-409e-a0e6-58adabe9123b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Senior Staff Systems Applications Engineer – Ethernet PHY')]</value>
      <webElementGuid>75f1d58f-d187-46e3-aa2f-2835ee0960ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jump to selected job details'])[1]/following::a[1]</value>
      <webElementGuid>2dcc868b-af24-4f45-991d-842a5258d7a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search for Jobs page is loaded'])[1]/following::a[1]</value>
      <webElementGuid>b1b72181-5c38-4a5b-a6a9-26ee1fb2353d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='locations'])[1]/preceding::a[1]</value>
      <webElementGuid>a7957e06-2daf-4ec4-b600-ca61ed3c645b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Santa Clara, CA'])[1]/preceding::a[1]</value>
      <webElementGuid>9b48e541-bf44-46db-8597-9ffa0266dcb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Senior Staff Systems Applications Engineer – Ethernet PHY']/parent::*</value>
      <webElementGuid>1638204b-bee6-4e19-8036-66a549f80b42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/en-US/MarvellCareers/job/Santa-Clara-CA/Senior-Staff-Systems-Applications-Engineer---Ethernet-PHY_2300850')]</value>
      <webElementGuid>951da15b-879d-440b-9c61-3c0f9aeceaea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h3/a</value>
      <webElementGuid>6a482dfe-9d8a-46a3-a292-0cced9b4008e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
