<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Search for Jobs_ac7r2</name>
   <tag></tag>
   <elementGuidId>e4469664-05b0-4cf8-a344-c0f6127dc5a6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ac7r2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ac7r2</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'text' and @aria-labelledby = '1b7e89b8-7f38-44b4-a331-b346ed9f7d2a']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e75cff45-c109-498a-81ae-20d3d70f26c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>559d107d-d2b9-4cfe-af8f-3b33a1ddf197</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-automation-id</name>
      <type>Main</type>
      <value>keywordSearchInput</value>
      <webElementGuid>86fe9981-8a08-43f5-8019-61a12fae82f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>1b7e89b8-7f38-44b4-a331-b346ed9f7d2a</value>
      <webElementGuid>88f8107f-d963-476b-b209-871561d4d040</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search for jobs or keywords</value>
      <webElementGuid>44896b4f-e553-4ecc-b173-286ac2fdf6eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ac7r2</value>
      <webElementGuid>6c4bc060-4a20-4a70-9cd4-a48cec66bb8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-1bl6yxh</value>
      <webElementGuid>f63d9f18-65bd-4255-a364-3bfe2faea7ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ac7r2&quot;)</value>
      <webElementGuid>5895a98c-a3ed-4cf3-b922-12ecd0acc6eb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ac7r2']</value>
      <webElementGuid>d6626965-a775-4871-b7b6-1582c736f5ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Search for jobs or keywords' and @id = 'ac7r2' and @class = 'css-1bl6yxh']</value>
      <webElementGuid>48bd579b-ae3c-49d4-81c8-7f538418df1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mainContent']/div/div/div/div/div/div/input</value>
      <webElementGuid>42699058-4897-4427-bf2a-7bfb4d4ddeb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>1135e2f2-44dd-4ccf-8431-d7d780521ab7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
