<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Auto</name>
   <tag></tag>
   <elementGuidId>a9058180-0140-4960-b17d-4de73186f4c0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>ul.bolt-text-columns-3 > li > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@href = '/personal/insurance/auto/' and (text() = 'Auto' or . = 'Auto')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>81006fe9-dd63-4731-a564-cc6f2b85a081</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/personal/insurance/auto/</value>
      <webElementGuid>bfb98d42-11ff-4dc4-9109-a85b41be8f01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_parent</value>
      <webElementGuid>5f1df9fe-595b-4e84-ae18-51e9d121f710</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Auto</value>
      <webElementGuid>275e99f8-5227-496f-ba3b-814c64d9dd71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header&quot;)/ul[3]/li[1]/div[@class=&quot;bolt-header-panel&quot;]/div[@class=&quot;bolt-header-panel-main&quot;]/div[@class=&quot;bolt-header-container&quot;]/div[@class=&quot;bolt-header-panel-links&quot;]/div[@class=&quot;bolt-header-panel-links-list bolt-w-100&quot;]/ul[@class=&quot;bolt-text-columns-3&quot;]/li[1]/a[1]</value>
      <webElementGuid>6bc3b635-b412-46f8-bc2b-d5c6fc4be372</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/personal/insurance/auto/' and (text() = 'Auto' or . = 'Auto')]</value>
      <webElementGuid>64760aa8-dc85-4aa5-91f8-137991600b67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//bolt-header[@id='header']/ul[3]/li/div/div/div/div[2]/div/ul/li/a</value>
      <webElementGuid>7df66a30-018d-45d5-804b-deacbd45e6cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Auto')]</value>
      <webElementGuid>c593ee29-80bd-4077-98e5-168953858ada</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vehicle products'])[1]/following::a[1]</value>
      <webElementGuid>aab23d67-3c8d-4546-a4dc-cecff628da10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Motorcycle'])[1]/preceding::a[1]</value>
      <webElementGuid>f8e34248-89c5-4a10-97a0-c2fd74c72e0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Snowmobile'])[1]/preceding::a[2]</value>
      <webElementGuid>77efd66f-86eb-4fdc-a2f1-aa22adb02cdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Auto']/parent::*</value>
      <webElementGuid>4fb7c504-1541-4132-ae4a-ef76bc870d50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/personal/insurance/auto/')]</value>
      <webElementGuid>c9eeee28-5eae-46d3-9874-6df21d0ad4d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ul/li/a</value>
      <webElementGuid>a3d059f6-8cdf-4f69-b76d-fc115d42ca62</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
