<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Vehicle</name>
   <tag></tag>
   <elementGuidId>7eafa67d-8fb4-41f3-8bdd-92d1a5e69dfb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.bolt-header-wc--nav-item</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@class = 'bolt-header-wc--nav-item' and (text() = 'Vehicle' or . = 'Vehicle')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d718cfcf-4cf7-4df1-81d6-549558012737</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bolt-header-wc--nav-item</value>
      <webElementGuid>7506e6b7-f90a-4483-8f5a-32de8b0bbe57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>79c75f16-bfa2-4c3b-acbb-524636c336e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Vehicle</value>
      <webElementGuid>7a3eb339-0276-4413-a095-07444e7cd604</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header&quot;)/ul[3]/li[1]/button[@class=&quot;bolt-header-wc--nav-item&quot;]</value>
      <webElementGuid>f4f9f135-7d26-468e-955c-2dc2e1805797</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@class = 'bolt-header-wc--nav-item' and (text() = 'Vehicle' or . = 'Vehicle')]</value>
      <webElementGuid>d31de736-b182-4ef6-8ece-df6cbf654355</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//bolt-header[@id='header']/ul[3]/li/button</value>
      <webElementGuid>0a28ba32-d8c2-4286-b2fa-d14033354779</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log in'])[1]/following::button[1]</value>
      <webElementGuid>775f01c0-7760-4470-9262-60d8e0a3f4d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search'])[1]/following::button[1]</value>
      <webElementGuid>b7dc2b68-e983-4730-a425-89e7ebb12926</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vehicle products'])[1]/preceding::button[1]</value>
      <webElementGuid>0336d56b-b92c-4872-a341-b719c5bbc6ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Vehicle']/parent::*</value>
      <webElementGuid>8da4bbbc-ab89-4aca-8074-78aeace0e3c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/button</value>
      <webElementGuid>bfc89ed2-d731-45a2-9065-b9f1026e4ed4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
