<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>cookieDisclousreButton</name>
   <tag></tag>
   <elementGuidId>8bb8b9d4-73a7-4761-8bef-7afd02d7b1f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@name='bluecoreCloseButton'])[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.close_button-173992-position.close_button-173992-position-d0.bcTextShadow > button[name=&quot;bluecoreCloseButton&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//button[@id='CookieTrackingDisclosureButton']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7c6ee213-36b1-4121-9979-2be231c01ffa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d9980615-1341-4054-ab90-10198d8cbcf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>bluecoreCloseButton</value>
      <webElementGuid>3d35cd01-9d09-4657-b8b3-879a72978711</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>close_button-173992-button close_button-173992-button-d2 close_button-173992-image close_button-173992-image-d3 bluecoreCloseButton</value>
      <webElementGuid>3517e93f-3573-42b6-80c4-f2df3e87753a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//button[@id='CookieTrackingDisclosureButton']</value>
      <webElementGuid>c14a8a17-f9ed-4739-b3ac-f765027748ac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@name='bluecoreCloseButton'])[3]</value>
      <webElementGuid>e5a73f6c-a19a-4f24-97de-533d6bbf3544</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='bluecoreActionScreen']/div[9]/button)[2]</value>
      <webElementGuid>b10b0f2c-82b2-4180-8e8b-4b3ee3b62658</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/div[9]/button</value>
      <webElementGuid>5bdb8f46-aef7-4d7a-91a6-59bf4485e656</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @name = 'bluecoreCloseButton']</value>
      <webElementGuid>c7dfbe2c-834d-4889-8108-aeae9e083e0c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
