<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>area_Shopping Cart Display Updated_SSCACloseBtn</name>
   <tag></tag>
   <elementGuidId>061057f6-5842-46c2-8c89-803e4c69c1d0</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//area[@id='SSCACloseBtn']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#SSCACloseBtn</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'SSCACloseBtn' and @title = 'Close']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>area</value>
      <webElementGuid>ce16313f-c293-4ecc-b194-d11c5326ebbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>shape</name>
      <type>Main</type>
      <value>rect</value>
      <webElementGuid>4cc078b8-e7c6-4f01-9288-7255bdddd96e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>coords</name>
      <type>Main</type>
      <value>2,265,317,636</value>
      <webElementGuid>a1f5a5b9-0f46-4d13-a5aa-ece76d26b1f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>SSCACloseBtn</value>
      <webElementGuid>9707b183-307d-43dd-bb5b-b945b0663ed1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_self</value>
      <webElementGuid>0c1fb4c3-0d05-4e84-9b10-aabd6904fa65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Close</value>
      <webElementGuid>5dd4a741-b323-42e9-b100-03428c9c88a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SSCACloseBtn&quot;)</value>
      <webElementGuid>ad0859fd-9c7d-457d-ad9b-75ee89d10468</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://assetshare.basspro.com/content/dam/bps-general-assets/web/2018/13637-canada-lightbox-landing-page/images/2020/BPS-lightbox-640x640.jpg</value>
      <webElementGuid>f0e0c58a-ce85-4631-879e-a7238c7b182f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//area[@id='SSCACloseBtn']</value>
      <webElementGuid>9c19229a-1230-4abf-99fd-b34aaa93142d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//map[@id='c_modal_contentMap']/area[2]</value>
      <webElementGuid>ed9125c2-51b4-4854-ab8e-a32a78c2d98f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//area[2]</value>
      <webElementGuid>dfda8663-a8cd-4276-82b5-c859b80c4ab1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//area[@id = 'SSCACloseBtn' and @title = 'Close']</value>
      <webElementGuid>c5217d59-87df-49ee-bf26-ac7cd45ff5f3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
