<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_3.7</name>
   <tag></tag>
   <elementGuidId>684cc374-ec07-4c18-90d4-85a5344010c5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='BPS_rating_summary']/div/button/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.bv_avgRating_component_container.notranslate</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0ac82da1-b023-483c-98fc-7d77031a2a93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>itemprop</name>
      <type>Main</type>
      <value>ratingValue</value>
      <webElementGuid>9646b28a-f17e-4244-981b-cea461f30e37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bv_avgRating_component_container notranslate</value>
      <webElementGuid>d6b3ee0c-19d7-4391-b3d0-e51ec764a13c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>3.7</value>
      <webElementGuid>3b2da235-9137-4f44-b7cd-f73542b33831</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BPS_rating_summary&quot;)/div[@class=&quot;bv_main_container&quot;]/button[@class=&quot;bv_main_container_row_flex bv_ratings_summary&quot;]/div[@class=&quot;bv_avgRating_component_container notranslate&quot;]</value>
      <webElementGuid>5cbfa494-e04f-42a0-b915-b88e4c335d6a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='BPS_rating_summary']/div/button/div[2]</value>
      <webElementGuid>657a9aa0-b47d-401e-976b-90eeb6ca234e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Muddy MTC100K Digital Trail Camera 2-Pack with SD Cards and Batteries Combo'])[3]/following::div[2]</value>
      <webElementGuid>f5f75b00-d9e7-44b9-930e-88026113dc31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Muddy MTC100K Digital Trail Camera 2-Pack with SD Cards and Batteries Combo'])[2]/following::div[6]</value>
      <webElementGuid>b6a257fe-8737-4c5b-b001-06fac41a7fff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(26)'])[1]/preceding::div[1]</value>
      <webElementGuid>ee8cd7a1-c836-4f02-a75b-c2865dfbe5b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Write a review'])[1]/preceding::div[3]</value>
      <webElementGuid>082a4d38-320b-493d-a3c1-1e66c1dd9739</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='3.7']/parent::*</value>
      <webElementGuid>8e2c3eb1-2111-4c35-bd1f-e4a41ff8b0b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/div[2]</value>
      <webElementGuid>0eb0d181-311f-457d-ba20-7d355e199769</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '3.7' or . = '3.7')]</value>
      <webElementGuid>46cf1efa-dd13-4fcb-be24-4d9a18b97d5e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
