<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Search_searchTerm</name>
   <tag></tag>
   <elementGuidId>864c0e50-9270-475e-8fe6-972b2bc41ef1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='SimpleSearchForm_SearchTerm']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#SimpleSearchForm_SearchTerm</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9f2cf431-72f9-4c2d-b215-33b347823c13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>SimpleSearchForm_SearchTerm</value>
      <webElementGuid>95ddf0e4-5e89-4a1c-8bb2-fcda45d068bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>9f5c89da-a08e-49d5-8c4f-fb8d69b47e44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>151d3734-dfb3-4d41-bbca-dd1c2232c758</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>searchTerm</value>
      <webElementGuid>b25133b4-a4c8-476f-b710-f7c5df34f5a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>What can we help you find?</value>
      <webElementGuid>7756fab2-d89d-4b2f-81cb-c15bae7023e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>d7277c14-1e61-404f-a115-2e88d4b7e3e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>focus-visible</value>
      <webElementGuid>c08d7434-ebc1-4f6a-8338-ffa0f575fff5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SimpleSearchForm_SearchTerm&quot;)</value>
      <webElementGuid>f3e88394-8206-4720-a85d-670f5efe427c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='SimpleSearchForm_SearchTerm']</value>
      <webElementGuid>b9a0cdef-e3df-4a6f-903b-790d69b1eae6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='searchTermWrapper']/input</value>
      <webElementGuid>4455814b-4572-4338-af82-197432fdec48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/input</value>
      <webElementGuid>0edff8bb-e0e1-4cfb-89cd-ae96f35d909c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'SimpleSearchForm_SearchTerm' and @type = 'text' and @name = 'searchTerm' and @placeholder = 'What can we help you find?']</value>
      <webElementGuid>8e28f6ae-edab-4f77-9a33-98554b2c5b23</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
