<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Yes, I have read and consent to the ter_cf053d</name>
   <tag></tag>
   <elementGuidId>a06f682e-ce92-4246-8056-3186fd414409</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@aria-label = 'Create Account' and @data-automation-id = 'click_filter']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.css-f0oaeo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>22611822-243d-482a-a1e3-04b36d35d114</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>font-size</name>
      <type>Main</type>
      <value>14</value>
      <webElementGuid>0fa0b706-58d6-45d8-a9cd-20dd2b285cc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>4ea7e37e-be57-4010-99ec-0b98269bddaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Create Account</value>
      <webElementGuid>20c5f46f-7e1d-424b-ad19-b8a89562677e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>796e1d13-b22a-4e27-86a6-d1f4e9016da6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>81947a60-5de5-411b-8774-53add94f2c5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-automation-id</name>
      <type>Main</type>
      <value>click_filter</value>
      <webElementGuid>109fdac0-1e28-41c1-8613-fef30aa3ec58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-f0oaeo</value>
      <webElementGuid>a8568701-82c9-4a85-8785-753487647e3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wd-Authentication-NO_METADATA_ID-uid6&quot;)/div[1]/div[@class=&quot;css-ecyovj&quot;]/div[1]/form[@class=&quot;css-w0sgi8&quot;]/div[@class=&quot;css-1s1r74k&quot;]/div[@class=&quot;css-1s1r74k&quot;]/div[1]/div[@class=&quot;css-1s1r74k&quot;]/div[@class=&quot;css-1s1r74k&quot;]/div[@class=&quot;css-f0oaeo&quot;]</value>
      <webElementGuid>d4cdce2e-cf06-40fd-83bb-9054c527eebc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@aria-label = 'Create Account' and @data-automation-id = 'click_filter']</value>
      <webElementGuid>483da401-274c-447f-888f-59ba992f55cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wd-Authentication-NO_METADATA_ID-uid6']/div/div/div/form/div[6]/div/div/div/div/div</value>
      <webElementGuid>bd8b9447-b0d3-4e55-84a1-0479cd67eea5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[6]/div/div/div/div/div</value>
      <webElementGuid>1decceba-5ede-47ce-aa73-231c581ea499</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
