<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Baitcast Reels</name>
   <tag></tag>
   <elementGuidId>2a6f654f-6f89-45b4-ba1d-35d0c091ad18</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='EspotContainer']/div/div/div/ul/li/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.subcat-panel-1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8c116560-0e3b-4724-81a8-28983045434c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>subcat-panel-1</value>
      <webElementGuid>e33a1cb7-0c0c-434b-b911-be8f7fe56104</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/l/baitcast-reels</value>
      <webElementGuid>18db171d-23ae-41a7-a7c9-cb782e8065ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Baitcast Reels</value>
      <webElementGuid>79cea92a-a071-4bbf-ba57-bf615fe7e122</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page&quot;)/div[@class=&quot;styles_Content__u25V0  styles_NoHeaderBanner__qv7WA&quot;]/div[@class=&quot;styles_ContentArea__hyULP&quot;]/div[@class=&quot;styles_CategoryPage__sEKFi styles_DepartmentPageContainer__zp5pK&quot;]/div[@class=&quot;styles_Slot__gWlDl styles_Slot4__NjyP7&quot;]/div[@id=&quot;EspotContainer&quot;]/div[@class=&quot;clp-subcategories&quot;]/div[@class=&quot;subcat&quot;]/div[@class=&quot;subcat-panel&quot;]/ul[@class=&quot;subcat-links&quot;]/li[1]/a[@class=&quot;subcat-panel-1&quot;]</value>
      <webElementGuid>a33e9425-fb6b-42f5-826f-72f77c8218a3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='EspotContainer']/div/div/div/ul/li/a</value>
      <webElementGuid>42759762-aff5-4238-85aa-454e22d8450f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Baitcast Reels')]</value>
      <webElementGuid>36558161-6393-46f1-b021-e51a2c05b3f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fishing Reels'])[1]/following::a[1]</value>
      <webElementGuid>3aa8f922-376d-4262-96e1-4b65f616bb5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fishing'])[3]/following::a[2]</value>
      <webElementGuid>238b7547-2d1f-46a4-a133-8cbf7accbf34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Spinning Reels'])[1]/preceding::a[1]</value>
      <webElementGuid>20a91c6c-39fd-49d0-93ab-4757fb0744bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Spincast Reels'])[1]/preceding::a[2]</value>
      <webElementGuid>826afb08-a8df-445f-83c5-01c9eb6cb4b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Baitcast Reels']/parent::*</value>
      <webElementGuid>87c6a562-552e-42db-96db-59c657aaac37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/l/baitcast-reels')]</value>
      <webElementGuid>83f6337a-b0dc-457d-8f62-563ffbacb7cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/div/div/div/ul/li/a</value>
      <webElementGuid>df823a88-aad1-4f1d-aa26-cedf2f9c937f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/l/baitcast-reels' and (text() = 'Baitcast Reels' or . = 'Baitcast Reels')]</value>
      <webElementGuid>44de571d-b602-433d-a880-cf33bae8cef4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
