<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_select one_1_2</name>
   <tag></tag>
   <elementGuidId>02070f4b-b7e4-4f31-bfd3-ec8513eda0da</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='input-11']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input-11</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>04571846-43dd-4c1d-9de3-e727bb99c5ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>67a799d8-970a-472c-af85-13b146a0a693</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>21eb2361-f619-4337-879c-fed77b95ae03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-automation-id</name>
      <type>Main</type>
      <value>phone-device-type</value>
      <webElementGuid>18779a39-640f-4f3d-83c5-756deafd1e2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-11</value>
      <webElementGuid>7d323688-0859-442a-8300-00d33f0602e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Phone Device Type select one required</value>
      <webElementGuid>7aeebf76-e205-45f7-b461-78123a2f52f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-1tpgct3</value>
      <webElementGuid>48dcc197-e776-4de4-a1cf-1195f3547d4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>select one</value>
      <webElementGuid>ebc1babe-3f2e-43fd-b593-24b0d5b60c22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-11&quot;)</value>
      <webElementGuid>14db5406-e0d7-4def-8e2a-98c3ccf0259c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='input-11']</value>
      <webElementGuid>7629f7b5-bc3a-41a9-b491-b9719892a4ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @data-automation-id = 'phone-device-type' and @id = 'input-11' and @aria-label = 'Phone Device Type select one required' and (text() = 'select one' or . = 'select one')]</value>
      <webElementGuid>cb9a578d-88b7-41c6-9ad8-81ff2b2f2617</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mainContent']/div/div[3]/div[2]/div[10]/div/div/div/div/button</value>
      <webElementGuid>61c4b170-f9f6-44a9-841b-2ffb79f426ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Phone'])[1]/following::button[1]</value>
      <webElementGuid>1c723ae9-ab21-4dd8-bd5d-fb73f9501735</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='select one']/parent::*</value>
      <webElementGuid>626ffd0f-bd75-4b56-ac7e-c684ecc1173e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/div/div/div/button</value>
      <webElementGuid>744d6f64-a6e7-4c15-a90a-7b84065d3d7c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
