<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Save and Continue</name>
   <tag></tag>
   <elementGuidId>82f4a52f-0d8b-4815-a451-d47730799c1a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@data-automation-id = 'bottom-navigation-next-button' and (text() = 'Save and Continue' or . = 'Save and Continue')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.css-1b3lfvr</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>62868f25-09be-4471-b0db-11bf9a3dbec5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-automation-id</name>
      <type>Main</type>
      <value>bottom-navigation-next-button</value>
      <webElementGuid>10ede755-959e-4db7-a111-3bd64f3b6906</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>font-size</name>
      <type>Main</type>
      <value>14</value>
      <webElementGuid>6c8199c9-d303-4777-b44c-539b9417f82c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>58b57bc9-f336-4a22-99d0-b737eef12d8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-1b3lfvr</value>
      <webElementGuid>12c9e90a-4dd7-4e11-8203-50ec9da8c370</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Save and Continue</value>
      <webElementGuid>288ce928-d049-4ed5-868b-3bf70701adab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainContent&quot;)/div[@class=&quot;css-2zfu5x&quot;]/div[@class=&quot;css-16g4x4b&quot;]/div[@class=&quot;css-poz4k7&quot;]/ul[@class=&quot;css-vcngj&quot;]/div[@class=&quot;css-0&quot;]/div[@class=&quot;css-1s1r74k&quot;]/div[@class=&quot;css-1s1r74k&quot;]/button[@class=&quot;css-1b3lfvr&quot;]</value>
      <webElementGuid>25817c21-b901-4655-a2a0-57a8d730bbe0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@data-automation-id = 'bottom-navigation-next-button' and (text() = 'Save and Continue' or . = 'Save and Continue')]</value>
      <webElementGuid>d3428f3d-dc1e-4dc6-b02b-d091e82e09eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mainContent']/div/div[5]/div/ul/div/div/div/button</value>
      <webElementGuid>c9b4937c-1f7e-4e6b-ae15-5b9db6592df2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='© 2023 Workday, Inc. All rights reserved.'])[1]/following::button[1]</value>
      <webElementGuid>94bbb403-cb4b-47c1-9a90-726fd617641f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Follow Us'])[1]/following::button[1]</value>
      <webElementGuid>f6857c92-57f7-4338-838e-e398af3a4215</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Save and Continue']/parent::*</value>
      <webElementGuid>29a48e5d-c993-440a-bd35-134bf60c8f46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul/div/div/div/button</value>
      <webElementGuid>eb6b9839-2e47-4fa9-8f09-f79edba7bba8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
