<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_select one_1</name>
   <tag></tag>
   <elementGuidId>52862d0a-9824-4141-b11d-3d13fe91d724</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='input-8']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input-8</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>18a26e9f-58b9-4056-bde5-1c8234240f11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>cd47c6d7-4710-4f6a-9488-c5d2e7ad080e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>280a0216-9728-4165-8eff-343eb7caa070</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-automation-id</name>
      <type>Main</type>
      <value>addressSection_countryRegion</value>
      <webElementGuid>a3639a44-728c-4702-8600-e42a780e6088</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-8</value>
      <webElementGuid>c2edf3e9-d432-4883-80e5-14ddee463e75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>State select one required</value>
      <webElementGuid>32be55b2-6aa0-4e3c-88fa-e9aff1b683c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-1tpgct3</value>
      <webElementGuid>8c609a66-0024-40ac-a705-78351f7e17d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>select one</value>
      <webElementGuid>9ff0e374-8dc4-4568-a0e7-e8577760f436</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-8&quot;)</value>
      <webElementGuid>9e77c05a-ec50-44e8-b6bd-f8fa6d35178b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='input-8']</value>
      <webElementGuid>6cbeb1be-fa09-474d-80b6-a3f23f105d0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @data-automation-id = 'addressSection_countryRegion' and @id = 'input-8' and @aria-label = 'State select one required' and (text() = 'select one' or . = 'select one')]</value>
      <webElementGuid>066250db-5193-4046-8291-ced68f33b956</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mainContent']/div/div[3]/div[2]/div[6]/div[3]/div/div/div/button</value>
      <webElementGuid>e66539da-975a-4b7d-9682-0e2ee818fccc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email Address'])[1]/preceding::button[1]</value>
      <webElementGuid>1cb84086-b527-4c8d-b36a-ab4e6cc36b88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='select one']/parent::*</value>
      <webElementGuid>dae5fa2d-c481-4eb0-929d-5484b50874bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[3]/div/div/div/button</value>
      <webElementGuid>3d6cf756-ba1d-42c3-aadf-da580251d83e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
