<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_United States of America</name>
   <tag></tag>
   <elementGuidId>1fce54f8-c678-40f1-b490-0ff4d229e49f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='input-2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input-2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a02c3afd-0e54-4d09-8816-a986b444fe17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>78dbfc6c-a1da-46e7-9348-b529d1343ae7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b52df91a-dc32-4a33-b0cc-28b7a0940099</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>bc33aa3152ec42d4995f4791a106ed09</value>
      <webElementGuid>dd520dc1-b538-4a60-9a7e-42aab306c3eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-automation-id</name>
      <type>Main</type>
      <value>countryDropdown</value>
      <webElementGuid>636fedd7-bce3-4e5a-be3c-2ef7411b4717</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-2</value>
      <webElementGuid>3742f580-d09e-4781-85df-13caaa18d9b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Country United States of America required</value>
      <webElementGuid>c5e16b90-d48d-4686-afea-c1616744315c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-1tpgct3</value>
      <webElementGuid>5ba05bdf-e2d1-4f82-a0d4-090ec15f4a52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>United States of America</value>
      <webElementGuid>e1acffe6-06ce-4731-af1a-1345fa4f52dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-2&quot;)</value>
      <webElementGuid>85969b5a-ff90-4cf7-9ed6-d8acfdf7c978</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='input-2']</value>
      <webElementGuid>1a5ceb79-c735-47f6-b6ad-47c6e165d528</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @data-automation-id = 'countryDropdown' and @id = 'input-2' and @aria-label = 'Country United States of America required' and (text() = 'United States of America' or . = 'United States of America')]</value>
      <webElementGuid>ccf04bb0-debe-4a50-bafa-b31983707e20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mainContent']/div/div[3]/div[2]/div[2]/div/div/div/button</value>
      <webElementGuid>168f3f0e-b0d7-4409-a831-73cce36f82c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Legal Name'])[1]/preceding::button[1]</value>
      <webElementGuid>4f4ea283-01f5-442a-bfc5-016b006f07aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='United States of America']/parent::*</value>
      <webElementGuid>b3441afc-f498-4f3e-99f2-194ec2af72d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/button</value>
      <webElementGuid>39341b12-0ec0-40df-9751-c9550b964f8e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
