<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Senior Staff Systems Applications Engineer  Ethernet PHY</name>
   <tag></tag>
   <elementGuidId>bc9c74fe-6525-4bd9-aa5f-deed4dd1a25f</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@data-automation-id = 'jobTitle' and @href = '/en-US/MarvellCareers/job/Santa-Clara-CA/Senior-Staff-Systems-Applications-Engineer---Ethernet-PHY_2300850' and (text() = 'Senior Staff Systems Applications Engineer – Ethernet PHY' or . = 'Senior Staff Systems Applications Engineer – Ethernet PHY')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.css-19uc56f</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@data-automation-id = 'jobTitle' and @href = '/en-US/MarvellCareers/job/Santa-Clara-CA/Senior-Staff-Systems-Applications-Engineer---Ethernet-PHY_2300850' and (text() = 'Senior Staff Systems Applications Engineer – Ethernet PHY' or . = 'Senior Staff Systems Applications Engineer – Ethernet PHY')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d3a13521-147a-47b5-86ec-f0a9a3ab6e7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-current</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>09e498ab-e1c2-4ec5-bdc2-cb6cd862a934</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-automation-id</name>
      <type>Main</type>
      <value>jobTitle</value>
      <webElementGuid>b4042cab-62ba-4fd5-a004-d006ffcbe7d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-uxi-element-id</name>
      <type>Main</type>
      <value>jobItem</value>
      <webElementGuid>539869f1-858c-47b9-85db-4ad7ebf515f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-uxi-query-id</name>
      <type>Main</type>
      <value>765a1cec-0053-435c-9ce7-3e12bf2e59d1</value>
      <webElementGuid>be8af15c-9a77-42e2-8a40-4f2703495f82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-uxi-widget-type</name>
      <type>Main</type>
      <value>heading</value>
      <webElementGuid>8e32e55c-1c92-49e8-9668-01f790d36fbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-19uc56f</value>
      <webElementGuid>d7631731-8298-4c76-a0b6-8b8af115edb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/en-US/MarvellCareers/job/Santa-Clara-CA/Senior-Staff-Systems-Applications-Engineer---Ethernet-PHY_2300850</value>
      <webElementGuid>564ebd40-f139-45ba-b453-14352a66a2b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Senior Staff Systems Applications Engineer – Ethernet PHY</value>
      <webElementGuid>0caa5798-1aa9-4a89-9f0b-6db713eec5fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainContent&quot;)/div[@class=&quot;css-b4ple3&quot;]/div[@class=&quot;css-uvpbop&quot;]/section[@class=&quot;css-8j5iuw&quot;]/ul[1]/li[@class=&quot;css-1q2dra3&quot;]/div[@class=&quot;css-qiqmbt&quot;]/div[@class=&quot;css-b3pn3b&quot;]/div[@class=&quot;css-b3pn3b&quot;]/h3[1]/a[@class=&quot;css-19uc56f&quot;]</value>
      <webElementGuid>ae431f11-bf50-42b9-ae63-fe35775934c5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@data-automation-id = 'jobTitle' and @href = '/en-US/MarvellCareers/job/Santa-Clara-CA/Senior-Staff-Systems-Applications-Engineer---Ethernet-PHY_2300850' and (text() = 'Senior Staff Systems Applications Engineer – Ethernet PHY' or . = 'Senior Staff Systems Applications Engineer – Ethernet PHY')]</value>
      <webElementGuid>01f64c0d-baa7-4573-995d-9efbd7161ea7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mainContent']/div/div[2]/section/ul/li/div/div/div/h3/a</value>
      <webElementGuid>6bd23c05-5e7f-4a9a-b325-6298d22a8060</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Senior Staff Systems Applications Engineer – Ethernet PHY')]</value>
      <webElementGuid>8c6e5939-90d9-4aed-a3cf-8b042ff09ff4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/en-US/MarvellCareers/job/Santa-Clara-CA/Senior-Staff-Systems-Applications-Engineer---Ethernet-PHY_2300850')]</value>
      <webElementGuid>3edb7531-e4bd-4bff-88f3-84c381e42a55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h3/a</value>
      <webElementGuid>ac99aa7a-d24f-4ec3-bda1-6c1c498413a0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
