<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Review</name>
   <tag></tag>
   <elementGuidId>a98cf0ee-fc28-4078-bbee-441cd029d7c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@data-automation-id = 'progressBarInactiveStep' and (text() = 'Review' or . = 'Review')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f6427936-7f9c-48a5-98e7-21b89ffb1435</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-automation-id</name>
      <type>Main</type>
      <value>progressBarInactiveStep</value>
      <webElementGuid>b6107d45-b4f9-408e-90c8-e9e601656c6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-1dczh83</value>
      <webElementGuid>ce49beff-3151-4ea9-a5af-ecc54f75d397</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Review</value>
      <webElementGuid>ee1770cc-34f8-4d51-9750-89a30692e210</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainContent&quot;)/div[@class=&quot;css-2zfu5x&quot;]/div[@class=&quot;css-nt23zb&quot;]/div[@class=&quot;css-3frnkb&quot;]/div[@class=&quot;css-1dczh83&quot;]</value>
      <webElementGuid>7d6112e9-1fb1-4dd9-844e-a0c90a61688d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@data-automation-id = 'progressBarInactiveStep' and (text() = 'Review' or . = 'Review')]</value>
      <webElementGuid>4805dd11-a72d-4618-9090-0f998857233d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mainContent']/div/div[2]/div/div[6]</value>
      <webElementGuid>8c375fdf-cb5a-4919-abf9-297b96e51003</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Self Identify'])[1]/following::div[1]</value>
      <webElementGuid>16364253-18bb-4a1e-8658-8dffa91a3f87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Voluntary Disclosures'])[1]/following::div[7]</value>
      <webElementGuid>75887b9e-03a7-4df6-b88f-933815584655</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Experience'])[2]/preceding::div[6]</value>
      <webElementGuid>92f42002-64ae-4071-b506-f10a47a37df3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[6]</value>
      <webElementGuid>d6b3e758-5bf8-413c-9acb-cc7728f8d626</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
