<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Gun_img</name>
   <tag></tag>
   <elementGuidId>8dd6dd90-6fd9-4e07-99f9-5206db7e641a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='EspotContainer']/div/div[7]/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;Scopes&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//img[@alt = 'Scopes']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>4757ae6b-945a-45f9-bbe0-a46113d23cd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Scopes</value>
      <webElementGuid>6a84220d-847b-49b8-bcf4-5427d898bd3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://assets.basspro.com/image/upload/c_scale,f_auto,q_auto,w_280/v1685051836/DigitalCreative/2023/Dept-Pages/Shooting/Guns_DeptBanners/Guns-Sub-Cat/used-guns-cab.jpg</value>
      <webElementGuid>33239a07-53c9-4b51-81eb-764a46171c7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page&quot;)/div[@class=&quot;styles_Content__u25V0  styles_NoHeaderBanner__qv7WA&quot;]/div[@class=&quot;styles_ContentArea__hyULP&quot;]/div[@class=&quot;styles_CategoryPage__sEKFi styles_SubCategoryPageContainer__ow_WR styles_IncludeDepSlot5__zwsYy&quot;]/div[@class=&quot;styles_Slot__gWlDl styles_Slot4__NjyP7&quot;]/div[@id=&quot;EspotContainer&quot;]/div[@class=&quot;sub-clp-subcats&quot;]/div[@class=&quot;subcat&quot;]/a[@class=&quot;subcat-breakout-7&quot;]/img[1]</value>
      <webElementGuid>005cb3c9-b89e-491c-bdfd-c63fa4175521</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='EspotContainer']/div/div[7]/a/img</value>
      <webElementGuid>314d5381-dfd7-4539-8adb-f8f99e73dd76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Scopes']</value>
      <webElementGuid>402a1a6f-3991-4131-80db-41c3db047314</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/a/img</value>
      <webElementGuid>5ed1cfad-8d6f-4f60-a227-466a9ef72a10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Scopes' and @src = 'https://assets.basspro.com/image/upload/c_scale,f_auto,q_auto,w_280/v1685051836/DigitalCreative/2023/Dept-Pages/Shooting/Guns_DeptBanners/Guns-Sub-Cat/used-guns-cab.jpg']</value>
      <webElementGuid>8f5838f1-521e-4fa1-8683-79eff0339c3e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
