<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Get a quote for_Zip1</name>
   <tag></tag>
   <elementGuidId>de3eab70-86d2-4e81-9d9a-fa62d936f5ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Auto</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Auto']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bf9bf668-4c89-4127-aeb7-396fbfb1e64a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>zip code</value>
      <webElementGuid>44fe6cd2-a36d-437d-a3ec-e2ada327970b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>AutoZip</value>
      <webElementGuid>5f7ea5bd-9a10-45d5-9546-ed082de46d21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Auto</value>
      <webElementGuid>c2ed42c8-9ce6-445d-a411-1c7eee2176a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>31b94aeb-b7d5-4a61-a797-adfd50a5ce02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>13639432-858c-4e31-8aae-4c8b758022de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>ZIP Code</value>
      <webElementGuid>4e780149-0b34-4e31-a488-41c415e9869f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Zip1</value>
      <webElementGuid>12718400-cb21-4760-92fd-8902094eb7b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>zip-field</value>
      <webElementGuid>389185b3-3333-43f9-ace4-c24c658b666c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AutoQuoteForm&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;column small-12 large-7&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;column small-12&quot;]/input[@id=&quot;Auto&quot;]</value>
      <webElementGuid>9a8f6ed8-9729-47ae-9064-f7de4a8e411a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Auto']</value>
      <webElementGuid>71b056ed-7df6-4463-9128-90b2e7e1589a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@aria-label = 'zip code' and @id = 'Auto' and @type = 'tel' and @placeholder = 'ZIP Code' and @name = 'Zip1' and @class = 'zip-field']</value>
      <webElementGuid>c9de0810-f5fd-4c07-971f-ce7e9b2a1f28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='AutoQuoteForm']/div/div/div/div/input</value>
      <webElementGuid>86e45bd5-5c77-4798-b706-8d50b9635c75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/input</value>
      <webElementGuid>70d5c5d3-221e-4af8-ae7c-bc5701bbb83c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
