<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Apply</name>
   <tag></tag>
   <elementGuidId>5f2db2b8-c294-4689-ae01-1156bdf41d49</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@href = 'https://marvell.wd2.myworkdayjobs-impl.com/en-US/MarvellCareers/details/Senior-Staff-Systems-Applications-Engineer---Ethernet-PHY_2300850/apply' and @data-automation-id = 'adventureButton' and (text() = 'Apply' or . = 'Apply')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.css-1meq8ta</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ebed2b9e-1320-45f5-83fd-cdae6e59b37e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://marvell.wd2.myworkdayjobs-impl.com/en-US/MarvellCareers/details/Senior-Staff-Systems-Applications-Engineer---Ethernet-PHY_2300850/apply</value>
      <webElementGuid>bba6c045-c4dc-4c2e-9eb6-f181a6fb8390</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>eba2bf63-f889-426a-a469-b48ca0ae53f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-automation-id</name>
      <type>Main</type>
      <value>adventureButton</value>
      <webElementGuid>0ea5a931-4b68-4b7f-9664-0bc24d300c7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>font-size</name>
      <type>Main</type>
      <value>14</value>
      <webElementGuid>0c3b04b1-0b74-4368-b73f-0cc92d662ba0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>c2b58b07-f0c7-44c8-988d-8ff4ff35ac4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-1meq8ta</value>
      <webElementGuid>d79899fe-79b1-4ae4-8fa6-3f36fd127006</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Apply</value>
      <webElementGuid>c29b54ba-8eea-4c91-b365-bf209b71a5a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainContent&quot;)/div[@class=&quot;css-b4ple3&quot;]/div[@class=&quot;css-uvpbop&quot;]/div[1]/div[@class=&quot;css-1s8xnc9&quot;]/section[@class=&quot;css-1v46q50&quot;]/div[@class=&quot;css-47ru22&quot;]/div[@class=&quot;css-6su6fj&quot;]/div[@class=&quot;css-2c41hv&quot;]/div[@class=&quot;css-1f9tql3&quot;]/div[@class=&quot;css-18k4i7e&quot;]/div[@class=&quot;css-37urdo&quot;]/div[@class=&quot;css-ipzqjw&quot;]/div[@class=&quot;css-b3pn3b&quot;]/div[@class=&quot;css-b3pn3b&quot;]/a[@class=&quot;css-1meq8ta&quot;]</value>
      <webElementGuid>da9f3de4-acdd-4022-9fd7-45ca71a6a04b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://marvell.wd2.myworkdayjobs-impl.com/en-US/MarvellCareers/details/Senior-Staff-Systems-Applications-Engineer---Ethernet-PHY_2300850/apply' and @data-automation-id = 'adventureButton' and (text() = 'Apply' or . = 'Apply')]</value>
      <webElementGuid>cea082b9-30f8-4739-b857-9e5e9f7ea5dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mainContent']/div/div[2]/div/div/section/div/div/div[3]/div/div/div[2]/div/div/div/a</value>
      <webElementGuid>ed127213-f601-4b5e-8fce-88b10de679fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Apply')]</value>
      <webElementGuid>19f8f53f-63ba-4cbd-92b7-4d31385f8c38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Senior Staff Systems Applications Engineer – Ethernet PHY'])[2]/following::a[2]</value>
      <webElementGuid>4d594b73-d3f6-4e98-b175-d865e223437a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Return to selected search result'])[1]/following::a[2]</value>
      <webElementGuid>3c686a20-c955-4e2a-bafa-d702d8d60311</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='locations'])[21]/preceding::a[1]</value>
      <webElementGuid>0dafef74-7718-48a2-8377-29dc3b5f5bda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Santa Clara, CA'])[7]/preceding::a[1]</value>
      <webElementGuid>b934e76b-44e9-469f-8cc5-03b7d4f25e52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Apply']/parent::*</value>
      <webElementGuid>7391531e-8996-4acd-8666-b182a8ecf0a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://marvell.wd2.myworkdayjobs-impl.com/en-US/MarvellCareers/details/Senior-Staff-Systems-Applications-Engineer---Ethernet-PHY_2300850/apply')]</value>
      <webElementGuid>3c344aa4-8adc-4ac0-b54a-6c40aed20737</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/a</value>
      <webElementGuid>5472fb66-c920-42fc-9838-447f1438dcf6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
