<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Senior Staff Systems Applications Enginee_9828fd</name>
   <tag></tag>
   <elementGuidId>488f82ab-8246-46eb-b860-6ebcea15c6b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@data-automation-id = 'jobTitle' and @href = '/en-US/MarvellCareers/job/Santa-Clara-CA/Senior-Staff-Systems-Applications-Engineer---Ethernet-PHY_2300850' and (text() = 'Senior Staff Systems Applications Engineer – Ethernet PHY' or . = 'Senior Staff Systems Applications Engineer – Ethernet PHY')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.css-19uc56f</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b00db786-7062-402b-8cd4-bc56b664beb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-current</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c97e5804-7ee7-4589-986d-de8d742f4ee9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-automation-id</name>
      <type>Main</type>
      <value>jobTitle</value>
      <webElementGuid>2e0bbcf7-3c9d-483a-b2e7-1aab140a4fdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-uxi-element-id</name>
      <type>Main</type>
      <value>jobItem</value>
      <webElementGuid>13676e32-8f93-4623-a509-3517346278f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-uxi-query-id</name>
      <type>Main</type>
      <value>c7f75832-3088-4fb4-8e2c-cc4a9b55d09b</value>
      <webElementGuid>55911dc7-d410-4f7c-b4e6-e2bfa2aeb932</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-uxi-widget-type</name>
      <type>Main</type>
      <value>heading</value>
      <webElementGuid>dde93862-b979-49e5-bae3-acc332c1dd1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-19uc56f</value>
      <webElementGuid>569db92e-5c26-4d87-9887-b9763a46dad6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/en-US/MarvellCareers/job/Santa-Clara-CA/Senior-Staff-Systems-Applications-Engineer---Ethernet-PHY_2300850</value>
      <webElementGuid>2503d16f-fa51-4814-aefc-34e6619ae221</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Senior Staff Systems Applications Engineer – Ethernet PHY</value>
      <webElementGuid>579044a8-41d7-43e5-916e-22b85ddaacb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainContent&quot;)/div[@class=&quot;css-b4ple3&quot;]/div[@class=&quot;css-uvpbop&quot;]/section[@class=&quot;css-8j5iuw&quot;]/ul[1]/li[@class=&quot;css-1q2dra3&quot;]/div[@class=&quot;css-qiqmbt&quot;]/div[@class=&quot;css-b3pn3b&quot;]/div[@class=&quot;css-b3pn3b&quot;]/h3[1]/a[@class=&quot;css-19uc56f&quot;]</value>
      <webElementGuid>2d814a00-9992-4caf-b202-d6cbf41fca50</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@data-automation-id = 'jobTitle' and @href = '/en-US/MarvellCareers/job/Santa-Clara-CA/Senior-Staff-Systems-Applications-Engineer---Ethernet-PHY_2300850' and (text() = 'Senior Staff Systems Applications Engineer – Ethernet PHY' or . = 'Senior Staff Systems Applications Engineer – Ethernet PHY')]</value>
      <webElementGuid>d70ad3c8-6b58-4b68-9559-bcf39933a757</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mainContent']/div/div[2]/section/ul/li/div/div/div/h3/a</value>
      <webElementGuid>abc392f9-26a6-48d1-a3ba-a3d6f5c53ac4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Senior Staff Systems Applications Engineer – Ethernet PHY')]</value>
      <webElementGuid>0080459a-c8c3-41ba-b54a-062c2bfcf2db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jump to selected job details'])[1]/following::a[1]</value>
      <webElementGuid>fdf5a799-0504-4f61-978b-7a3ef7168514</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search for Jobs page is loaded'])[1]/following::a[1]</value>
      <webElementGuid>20cab8af-53f9-47c7-a5cf-ab7a01d30fd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='locations'])[1]/preceding::a[1]</value>
      <webElementGuid>9c859a79-b34b-4130-b178-5c41603ee391</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Santa Clara, CA'])[1]/preceding::a[1]</value>
      <webElementGuid>2218edc7-948c-4f49-bae6-1d7bceb9830b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Senior Staff Systems Applications Engineer – Ethernet PHY']/parent::*</value>
      <webElementGuid>903ca828-a49c-4036-b802-4daec97896d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/en-US/MarvellCareers/job/Santa-Clara-CA/Senior-Staff-Systems-Applications-Engineer---Ethernet-PHY_2300850')]</value>
      <webElementGuid>bb6354ea-93bc-4752-997d-49436defbd57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h3/a</value>
      <webElementGuid>e39b703d-e25a-4657-b5e5-91335a3672b4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
