<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Search for Jobs_mm4z2</name>
   <tag></tag>
   <elementGuidId>45e021a5-414d-400c-bd6c-8e4eda51cfd1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mm4z2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mm4z2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cf996520-8efe-4c63-a7a2-c4a5fd554bef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b0681978-4b52-4632-85cc-782eda1e6f9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-automation-id</name>
      <type>Main</type>
      <value>keywordSearchInput</value>
      <webElementGuid>b2ae6394-8fe8-4dc7-8962-5c1d25a970da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>006d2ac3-a605-4242-ad4f-6addb7438d7f</value>
      <webElementGuid>1de588dc-a876-4d61-b46a-5d8abe5ef407</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search for jobs or keywords</value>
      <webElementGuid>287dd545-a902-46ad-b166-2c3fe525782c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mm4z2</value>
      <webElementGuid>e0145430-a13a-421e-9409-810b4e9c94cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-1bl6yxh</value>
      <webElementGuid>6ad34330-4472-4063-b760-b0370d0cf273</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mm4z2&quot;)</value>
      <webElementGuid>d2af0267-783e-423f-a596-2d9e2f2d8791</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mm4z2']</value>
      <webElementGuid>9bfda5d4-6276-4139-8869-1f7e65a9104f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @data-automation-id = 'keywordSearchInput' and @placeholder = 'Search for jobs or keywords' and @id = 'mm4z2']</value>
      <webElementGuid>5c935430-0e19-40d0-8990-70cccc5794a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mainContent']/div/div/div/div/div/div/input</value>
      <webElementGuid>ca5c9dbb-480a-4343-a458-6cd685ba2e12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>4d9b7db2-9b95-412c-9fd2-0057cb670f94</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
